[package]
name = "rust_gtk4_boilerplate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.4.8"
gio = "0.15.12"
glib = "0.15.12"
